### ISSUE TITLE
Compatibility certification request for Hibernate Validator for Validation 3.1.0

### ISSUE THREAD

**Issue by starksm64** [jakartaee/validation-spec#281]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  Red Hat, https://www.jboss.org/
- [x] Product Name, Version and download URL (if applicable):<br/>
  Hibernate Validator, 8.0.1.Final, http://hibernate.org/validator/releases/8.0/
- [x] Specification Name, Version and download URL:<br/>
   Jakarta Bean Validation 3.1, https://jakarta.ee/specifications/bean-validation/3.1/
- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
  3.1.0, 32d008ee99e28325ef92761891112b7177ad2b6c31881216baa0f3729a8eda03
  https://download.eclipse.org/ee4j/bean-validation/3.1/validation-tck-dist-3.1.0.zip
- [x] Public URL of TCK Results Summary:<br/>
  https://github.com/jakartaredhat/beanvalidation-tck/wiki/Jakarta-Bean-Validation-3.1-TCK-Results
  Includes both Java SE 17 and 21 runs
- [x] Java runtime used to run the implementation:<br/>
    openjdk version "21.0.2" 2024-01-16 LTS
    OpenJDK Runtime Environment Temurin-21.0.2+13 (build 21.0.2+13-LTS)
    OpenJDK 64-Bit Server VM Temurin-21.0.2+13 (build 21.0.2+13-LTS, mixed mode, sharing)

    openjdk version "17.0.10" 2024-01-16
    OpenJDK Runtime Environment Temurin-17.0.10+7 (build 17.0.10+7)
    OpenJDK 64-Bit Server VM Temurin-17.0.10+7 (build 17.0.10+7, mixed mode, sharing)
- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  EF CI environment
 Linux basic-497lf 6.2.9-300.fc38.x86_64 SMP PREEMPT_DYNAMIC Thu Mar 30 22:32:58 UTC 2023 x86_64 GNU/Linux
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by ivargrimstad** [comment]
Link to TCK should be https://download.eclipse.org/ee4j/bean-validation/3.1/validation-tck-dist-3.1.0.zip

**Comment by ivargrimstad** [comment]
> Link to TCK should be https://download.eclipse.org/ee4j/bean-validation/3.1/validation-tck-dist-3.1.0.zip

Also applies to the TCK Results page

**Comment by starksm64** [comment]
Links have been updated
