### ISSUE TITLE
Finalize the release of Jakarta Validation 3.1

### ISSUE THREAD

**Issue by ivargrimstad** [jakartaee/validation-spec#283]
### Project team:
 - [x] promotes api staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
 - [x] go through the merged jakarta.ee specification website page to verify all the links are valid.
 - [x] if XML Schemas are published on https://jakarta.ee/schemas, send a PR to update the status from `Draft` to `Final`.
 - [x] approve the compatibility request.
 - [x] merge any final release branch as appropriate for the branch management for the project.

**Comment by ivargrimstad** [comment]
When can we expect the api artifact in Maven Central @starksm64?

**Comment by starksm64** [comment]
All tasks are complete
